-- Generated by Palette Forge
return {
  {
    "folke/tokyonight.nvim",
    opts = {
      style = "night",
      on_colors = function(c)
        c.bg = "#33363C"
        c.bg_dark = "#2F3237"
        c.bg_float = "#383C42"
        c.bg_sidebar = "#2F3237"
        c.bg_statusline = "#2F3237"
        c.fg = "#F2F6F3"
        c.fg_dark = "#D2D9D4"
        c.fg_gutter = "#818C84"
        c.border = "#FF6678"
        c.comment = "#67736B"
        c.orange = "#FF6678"
        c.yellow = "#F2C16F"
        c.red = "#FF2F6F"
        c.blue = "#D0C1FF"
        c.cyan = "#84EBC9"
        c.green = "#CFF075"
        c.magenta = "#9C82FF"
      end,
      on_highlights = function(hl, c)
        hl.Normal = { bg = c.bg, fg = c.fg }
        hl.NonText = { fg = c.comment }
        hl.Comment = { fg = c.comment, italic = true }
        hl.LineNr = { fg = c.fg_gutter }
        hl.CursorLineNr = { fg = c.orange, bold = true }
        hl.CursorLine = { bg = "#383C42" }
        hl.Visual = { bg = "#3D4148" }
        hl.StatusLine = { bg = c.bg_dark, fg = c.fg }
        hl.StatusLineNC = { bg = c.bg_dark, fg = c.comment }
        hl.WinSeparator = { fg = c.border }
        hl.TabLine = { bg = c.bg_dark, fg = c.comment }
        hl.TabLineSel = { bg = c.cyan, fg = c.bg }
        hl.TabLineFill = { bg = c.bg_dark }
        hl.DiagnosticWarn = { fg = c.yellow }
        hl.DiagnosticError = { fg = c.red }
        hl.DiagnosticInfo = { fg = c.cyan }
        hl.DiagnosticHint = { fg = c.magenta }
        hl.DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true }
        hl.DiagnosticUnderlineError = { sp = c.red, undercurl = true }
        hl.DiagnosticUnderlineInfo = { sp = c.cyan, undercurl = true }
        hl.DiagnosticUnderlineHint = { sp = c.magenta, undercurl = true }
        hl.Pmenu = { bg = "#2F3237", fg = c.fg_dark }
        hl.PmenuSel = { bg = c.cyan, fg = c.bg }
        hl.Search = { bg = c.orange, fg = c.bg }
        hl.IncSearch = { bg = c.yellow, fg = c.bg }
        hl.MatchParen = { fg = c.orange, bold = true }
      end,
    },
  },
  {
    "LazyVim/LazyVim",
    opts = { colorscheme = "tokyonight" },
  },
}
